name: Run Python Script Every Hour

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour at minute 0
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  run_python_script:
    runs-on: ubuntu-latest  # You can choose the OS for your job (e.g., ubuntu-latest)

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Use the Python version you need

    # Step 3: Install dependencies (if you have any)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Make sure you have a requirements.txt file
        
    - name: Set up Firebase credentials
      run: |
        echo "{" > firebase_credentials.json
        echo "\"type\": \"${{ secrets.FIREBASE_TYPE }}\"," >> firebase_credentials.json
        echo "\"project_id\": \"${{ secrets.FIREBASE_PROJECT_ID }}\"," >> firebase_credentials.json
        echo "\"private_key_id\": \"${{ secrets.FIREBASE_PRIVATE_KEY_ID }}\"," >> firebase_credentials.json
        echo "\"private_key\": \"${{ secrets.FIREBASE_PRIVATE_KEY }}\"," >> firebase_credentials.json
        echo "\"client_email\": \"${{ secrets.FIREBASE_CLIENT_EMAIL }}\"," >> firebase_credentials.json
        echo "\"client_id\": \"${{ secrets.FIREBASE_CLIENT_ID }}\"," >> firebase_credentials.json
        echo "\"auth_uri\": \"${{ secrets.FIREBASE_AUTH_URI }}\"," >> firebase_credentials.json
        echo "\"token_uri\": \"${{ secrets.FIREBASE_TOKEN_URI }}\"," >> firebase_credentials.json
        echo "\"auth_provider_x509_cert_url\": \"${{ secrets.FIREBASE_AUTH_PROVIDER_URL }}\"," >> firebase_credentials.json
        echo "\"client_x509_cert_url\": \"${{ secrets.FIREBASE_CIENT_URL }}\"" >> firebase_credentials.json
        echo "\"universe_domain\": \"${{ secrets.FIREBASE_UNIVERSE_DOMAIN }}\"" >> firebase_credentials.json
        echo "}" >> firebase_credentials.json
    # Step 4: Run your Python script
    - name: Run Python script
      run: python get_top_100_stocks.py  # Replace with the actual path to your Python script

    - name: Cleanup Firebase credentials
      run: rm firebase_credentials.json


